### ISSUE TITLE
Add support for lines

### ISSUE THREAD

**Issue by mgold** [johnpmayer/elm-webgl#14]
2D lines are useful for axes and grids. I've looked through the library and I think this is possible without changing the compiler or a breaking change. I think you could

* Add a function `line : Color -> Vec3 -> Vec3 -> Entity` (or maybe `List Vec3`). The JS object produced would be different from that for a mesh, but in Elm it's an opaque type.

* Add a case to `drawEntity` to handle this alternate construct. One of many examples online is [here](http://www.codeproject.com/Articles/594222/LineplusinplusWebGLplusandpluswhyplusyouplusgonnap).

You could probably do points in a similar fashion (useful for dense grids without cluttering things visually).

Do you think this is reasonable and feasible? Thanks.

**Comment by johnpmayer** [comment]
Should be covered in #27
