### ISSUE TITLE
Mouse.position change not reflected 

### ISSUE THREAD

**Issue by wighawag** [johnpmayer/elm-webgl#17]
Hi,

Finally found some time to play with your webgl library and it is great.

I found an issue, not sure if it is a webgl-elm or elm issue but with the code below I got the following behavior
http://ibin.co/1qp7HBTcTGBJ

where the red arrow indicate the mouse pointer position.

This happen when I move the mouse pointer suddenly.
If I move the pointer again it still reset to the correct behaviour:
the screen is filled from the top left corner (As it should)

It seems like there is an issue with webgl not being updated properly after the signal from the Mouse position

```Elm
import Mouse
import Window
import Signal (map, map2)
import Text (asText)
import WebGL as GL
import Math.Vector3 (..)
import Math.Vector2 (..)
import Math.Matrix4 as Mat4
import Graphics.Element (..)

main = map view Mouse.position 


type alias Vertex = { position : Vec2, color : Vec3 }

mesh : List (GL.Triangle Vertex)
mesh =
    [ ( Vertex (vec2 0  0 ) (vec3 1 0 0)
      , Vertex (vec2 1  1 ) (vec3 0 1 0)
      , Vertex (vec2 1 0 ) (vec3 0 0 1)
      ),
      ( Vertex (vec2 0  0 ) (vec3 1 0 0)
      , Vertex (vec2 0  1 ) (vec3 0 0 1)
      , Vertex (vec2 1 1 ) (vec3 0 1 0)
      )
    ]


ortho2D w h = Mat4.makeOrtho2D 0 w h 0

    
   
view : (Int,Int)  -> Element 
view (w,h) =
  let matrix = ortho2D 1 1
  in GL.webgl (w,h)
    [ GL.entity vertexShader fragmentShader mesh { mat = matrix } ]


-- Shaders

vertexShader : GL.Shader { attr | position:Vec2, color:Vec3 } { unif | mat:Mat4.Mat4 } { vcolor:Vec3 }
vertexShader = [glsl|

attribute vec2 position;
attribute vec3 color;
uniform mat4 mat;
varying vec3 vcolor;

void main () {
    gl_Position = mat * vec4(position, 0.0, 1.0);
    vcolor = color;
}

|]


fragmentShader : GL.Shader {} u { vcolor:Vec3 }
fragmentShader = [glsl|

precision mediump float;
varying vec3 vcolor;

void main () {
    gl_FragColor = vec4(vcolor, 1.0);
}

|]
```

**Comment by johnpmayer** [comment]
I wasn't able to reproduce after updating the code to 0.15.1 - what's the behavior specifically?

There's definitely some flickering when you resize the context, because that's going to create lots of new elements (I think, maybe not, at the very least, it's doing lots of DOM manipulation)
