### ISSUE TITLE
Need Access to RenderingContext to change blendmode

### ISSUE THREAD

**Issue by hughfdjackson** [johnpmayer/elm-webgl#30]
I'm making a small 2d game on top of webgl - which requires a change in blend-mode to respect the transparency of the pngs I'm using as a texture: 

```
gl.enable( gl.BLEND );
gl.blendEquation( gl.FUNC_ADD );
gl.blendFunc( gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA );
```

I'm totally happy to do the work to add hooks to let the user configure this, but I'm not 100% sure how that API should look on the Elm side.  

Is there any interest in exposing this sort of configuration, and suggestions on how that should look on the elm side?

**Comment by GlenDC** [comment]
I was interested in the same thing. I was going to explore it today among other things. Will let you know how far I get with it.

**Comment by GlenDC** [comment]
I managed to come up with a way that satisfies me and after cleaning it up and documenting all I did, I made a pull request with my commit: [https://github.com/johnpmayer/elm-webgl/pull/32](https://github.com/johnpmayer/elm-webgl/pull/32). You can find a description, the commit and an example of how your request is now possible. Would be more than happy to hear your and others feedback on this to get an agreement and get this functionality or similar functionality in the mainline.

**Comment by johnpmayer** [comment]
As #32 is merged, I think this should be supported
